There has been a new listing created on Zen:

Name: <?php echo $name; ?>
Location: <?php echo $location ?>, <?php echo $country ?>
Stage: <?php echo $stage ?>
Link: http://zen.coderdojo.com/dojo/<?php echo $dojo_id ?>
This was automatically generated by zen.coderdojo.com